#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  7 10:29:57 2020

@author: dohertyguirand
"""


import csv
csv_file = 'primes1.csv'
txt_file = 'primes.txt'
with open(txt_file, "w+") as my_output_file:
    with open(csv_file, "r") as my_input_file:
        [ my_output_file.write(" ".join(row)+'\n') for row in csv.reader(my_input_file)]
    my_output_file.close()